# config_evaluate.yaml

model:
  type: "checkpoint"
  path: " "
  path_TorchScript: " "


test:
  data_dir:
  batch_size: 64
  num_workers: 4

transform:
  resize: [224, 224]
  normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]

dataset:
  raw: true  # Set to true to enable label normalization; set to false to disable
